### ISSUE TITLE
Datamodel stuff for TA2

### ISSUE THREAD

**Issue by jpfairbanks** [DARPA-ASKEM/data-model#1]
Changes that I would like based on our meeting today.

1. modeling.representations instead of modeling.intermediates, because they are all fully fledged models
2. modeling.frameworks for storing the different frameworks. This should have at least a schema column for how you represent the data of the models and a semantics column for how you are supposed to interpret it. For example `petri, mass-action` for a petri net with mass action kinetics differential equations semantics.
3. modeling.runtimes each software package should advertise what framework it supports. For example `algebraicpetri.jl:solve` would support the runtime of `petri, mass-action`
4. `modeling.models` should be an index into the `modeling.operations` table. 
5. `modeling.operations` as a blob table is fine for v0

**Comment by fivegrant** [comment]
Good suggestions @jpfairbanks. I tried to incorporate all your feedback into [the most recent commit](https://github.com/DARPA-ASKEM/data-model/commit/1abf010bf604ed79c977dda491a977ab778beaea). The only point I didn't put into the ERD is (3). Please let me know if you think the other changes are adequate, especially the framework metadata table and its one to many relationship.

**Comment by brandomr** [comment]
For #3 it sounds like the general flow is that the user can pick the framework (e.g. "I'm working on a petri net") and then can select a software backend (e.g. `algebraicpetri`). If that's about right we can definitely implement it. I do wonder if we'd need/want an analog for simulation softwares/systems (e.g. "Pyro can be used to solve xyz types of problems")

**Comment by jpfairbanks** [comment]
Yeah I think there is basically a graph of modeling frameworks. Every model Ives in a representational framework C and then there are ways to interpret it as a model in some other framework D. F:C->D is like an edge that says interpreter F can interpret any model in C as a model in D. For example Mass Action Kinetics interprets a Petri Net as an ODE.

We will have a similar story for simulators S:M->R that says that when you run simulator S on a model in class M you get a result of type R.

Having these there pieces of info will be really important for deciding when you can compose frameworks. For example, we can take a MAK: Petri -> ODE and then Eul: ODE -> DDS and compose them to go Petri->DDS by applying Eulers method to solve an ODE you get from the MAK applied to a Petri net.

**Comment by fivegrant** [comment]
I think the data model handles your requested needs @jpfairbanks . I'm going to close this issue for now, but I will reopen if you note that one of your points still isn't handled.
